### ISSUE TITLE
OneDrive link for Data Preparation

### ISSUE THREAD

**Issue by qjadud1994** [Eli-YiLi/PMM#1]
Thank you for sharing your great work!

Now, I gonna try to run your source code, however, the OneDrive link is not valid.

Could you update the link or share using other cloud services such as google-drive or dropbox?

I cannot access Baidu :(

**Comment by Eli-YiLi** [comment]
OneDrive link is updated.

COCO is too large, only baidu cloud meets the capacity.
If you know any cloud service whose capacity is more than 20GB for free, please tell to me, tks.
BaiduCloud requires to download a client.

I prepared the converted GT and image labels. If you are not able to download from BaiduCloud, you can download it from official website and convert the GT to VOC format (PNG) with label dict in numpy format.

**Comment by qjadud1994** [comment]
Thank you for your rapid reply!

For now, VOC dataset is enough for me.

Thanks.
