### ISSUE TITLE
About args.gen_seg_mask

### ISSUE THREAD

**Issue by ZechengLi19** [Eli-YiLi/PMM#10]
When I generate mask on COCO2017. It seems need to a lot of time to finish this work. I use 8 T4 or 2 RTX3090 to test the speed. Both of them get 200 .npy files for an hour. It means I need nearly 11 days to generate mask. Could you tell me. What can I do for speed up this code？Thanks.

**Comment by Eli-YiLi** [comment]
You can reduce the number of scales in multiscale test, especially high resize scale.
But the performance is not promised, you'd better check the performance on a tiny subset.
Note that I ran it on 4 x 8 1080Ti (similar to 8 3090Ti).

**Comment by ZechengLi19** [comment]
Thanks! And I want to know, how long did you spend for generating mask?
