### ISSUE TITLE
COCO inference results

### ISSUE THREAD

**Issue by NRPerson** [Eli-YiLi/PMM#12]
Hi, thanks for the great work. But when I predict the result based on the released weights, it is difficult to find the person category. And the IoU of person is 0, why?

**Comment by Eli-YiLi** [comment]
Yes, I find some categories are at 0 mIoU, but I didn't analyze this problem.  I guess scores of person are relatively low, and other categories are dominant in argmax. This phenomenon is obvious when the category number is large.
