### ISSUE TITLE
coco train_voc_format or cls_labels.

### ISSUE THREAD

**Issue by mongeoroo** [Eli-YiLi/PMM#14]
Hi, thanks for your great work.

while I trained the scalenet101 with SEAM, it can't capture the person. 

The model only localizes the corner of the image for the person's CAM.

And I used the pre-trained weight.

Thanks.

**Comment by Eli-YiLi** [comment]
Yes, I find some categories are at 0 mIoU, but I didn't analyze this problem. I guess scores of person are relatively low, and other categories are dominant in argmax. This phenomenon is obvious when the category number is large.
