### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by zwy1996** [Eli-YiLi/PMM#3]
Hi, Thanks for your code!

When I used your code to run experiments on the COCO dataset. We used the 8  v100 32g  card. Although I set the bs=4,
When infer, eval cam and PPMG, I had met the following error, 

THCudaCheck FAIL file=/pytorch/aten/src/THC/THCCachingHostAllocator.cpp line=296 error=2 : out of memory
Segmentation fault (core dumped)

Could you please give me some advice?

Best wishes to you!

**Comment by Eli-YiLi** [comment]
It seems not related to GPU, because GPU reports "CUDA out of memory" if batch size is too large.

Try to check the memory of server. If you run on docker, try to add "--ipc=host" when run docker to cancel the memory limitation.

**Comment by zwy1996** [comment]
Thanks for your advice.

Now, I run normally!

**Comment by zwy1996** [comment]
Hi,

I was very sorry to bother you. I had some confusion now . In your paper, I have not seen the pure weak supervision result on COCO dataset， I knew other paper also did not offer it, Would you please tell it?  I wanted to have a preparation.

Best wishes to you!

**Comment by Eli-YiLi** [comment]
I provide pseudo-mask of COCO in WSSS_MMSeg, you can evaluate and use it.

![图片](https://user-images.githubusercontent.com/49093246/138630233-2c75d413-e17f-43ed-981c-e625a0b57d30.png)

**Comment by zwy1996** [comment]
Hi, nice work!

When I read your code in the " infer_multi_crop.py"
line 80-82
 cam_dict = {}
        for i in range(args.num_cls-1):
            if label[i] > 1e-5:
                cam_dict[i] = norm_cam[i].astype(np.float16)

Did this mean that you use the image level information for the pseudo segmentation label？Did you follow other paper？

Thank you very much!

**Comment by Eli-YiLi** [comment]
In mask generation of train_sug set, image-level tags are needed.

I follow SEAM, and many papers do like this.
