### ISSUE TITLE
the lost document

### ISSUE THREAD

**Issue by liping-ren** [Eli-YiLi/PMM#5]
Hello ，thanks to the code release.But I cannot find the models and coco14 document.I am looking for the ones .thank you.
Best wishes to you
![捕获](https://user-images.githubusercontent.com/81289225/147104001-6138fbe1-9c12-4e08-b707-bac45216dda3.PNG)

**Comment by Eli-YiLi** [comment]
Please download the provided data and weights, and ln -s after decompression.
![图片](https://user-images.githubusercontent.com/49093246/147181008-2595119a-129f-4fdb-add6-3eb1b8a33552.png)
